<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.26.3 (20100126.1600)
 -->
<!-- Title: G Pages: 1 -->
<svg width="632pt" height="792pt"
 viewBox="0.00 0.00 631.88 792.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph1" class="graph" transform="scale(0.277505 0.277505) rotate(0) translate(4 2850)">
<title>G</title>
<polygon fill="white" stroke="white" points="-4,5 -4,-2850 2274,-2850 2274,5 -4,5"/>
<!-- Schuldrecht -->
<g id="node1" class="node"><title>Schuldrecht</title>
<polygon fill="none" stroke="black" points="1355,-2846 1257,-2846 1257,-2810 1355,-2810 1355,-2846"/>
<text text-anchor="middle" x="1306" y="-2823.9" font-family="Times Roman,serif" font-size="14.00">Schuldrecht</text>
</g>
<!-- Vorraussetzungen -->
<g id="node2" class="node"><title>Vorraussetzungen</title>
<polygon fill="none" stroke="black" points="1212.5,-2688.5 1212.5,-2771.5 1399.5,-2771.5 1399.5,-2688.5 1212.5,-2688.5"/>
<text text-anchor="middle" x="1306" y="-2738.9" font-family="Times Roman,serif" font-size="14.00"> Vorraussetzungen:</text>
<polyline fill="none" stroke="black" points="1212.5,-2730.5 1399.5,-2730.5 "/>
<text text-anchor="middle" x="1306" y="-2697.4" font-family="Times Roman,serif" font-size="14.00"> Geschäftsfähigkeit §104</text>
</g>
<!-- Schuldrecht&#45;&gt;Vorraussetzungen -->
<g id="edge2" class="edge"><title>Schuldrecht&#45;&gt;Vorraussetzungen</title>
<path fill="none" stroke="black" stroke-width="2" d="M1306,-2809.57C1306,-2801.5 1306,-2791.59 1306,-2781.54"/>
<polygon fill="black" stroke="black" points="1309.5,-2781.51 1306,-2771.51 1302.5,-2781.51 1309.5,-2781.51"/>
</g>
<!-- Willenserklärung -->
<g id="node3" class="node"><title>Willenserklärung</title>
<polygon fill="none" stroke="black" points="1208,-2368.5 1208,-2649.5 1404,-2649.5 1404,-2368.5 1208,-2368.5"/>
<text text-anchor="middle" x="1306" y="-2616.9" font-family="Times Roman,serif" font-size="14.00"> Willenserklärung:</text>
<polyline fill="none" stroke="black" points="1208,-2608.5 1404,-2608.5 "/>
<text text-anchor="middle" x="1306" y="-2575.9" font-family="Times Roman,serif" font-size="14.00"> geheimer Vorbehalt §116</text>
<polyline fill="none" stroke="black" points="1208,-2567.5 1404,-2567.5 "/>
<text text-anchor="middle" x="1306" y="-2550.9" font-family="Times Roman,serif" font-size="14.00">Scheingeschäft §117</text>
<polyline fill="none" stroke="black" points="1208,-2542.5 1404,-2542.5 "/>
<text text-anchor="middle" x="1306" y="-2509.9" font-family="Times Roman,serif" font-size="14.00"> Scherzerklärung §118</text>
<polyline fill="none" stroke="black" points="1208,-2501.5 1404,-2501.5 "/>
<text text-anchor="middle" x="1306" y="-2484.9" font-family="Times Roman,serif" font-size="14.00">Formmangel §125ff</text>
<polyline fill="none" stroke="black" points="1208,-2476.5 1404,-2476.5 "/>
<text text-anchor="middle" x="1306" y="-2443.9" font-family="Times Roman,serif" font-size="14.00"> gesetzl. Verbot §134</text>
<polyline fill="none" stroke="black" points="1208,-2435.5 1404,-2435.5 "/>
<text text-anchor="middle" x="1306" y="-2418.9" font-family="Times Roman,serif" font-size="14.00">Sittenwidrigkeit §138</text>
<polyline fill="none" stroke="black" points="1208,-2410.5 1404,-2410.5 "/>
<text text-anchor="middle" x="1306" y="-2377.4" font-family="Times Roman,serif" font-size="14.00"> Auslegung §133</text>
</g>
<!-- Vorraussetzungen&#45;&gt;Willenserklärung -->
<g id="edge4" class="edge"><title>Vorraussetzungen&#45;&gt;Willenserklärung</title>
<path fill="none" stroke="black" stroke-width="2" d="M1306,-2688.43C1306,-2679.8 1306,-2670.24 1306,-2660.16"/>
<polygon fill="black" stroke="black" points="1309.5,-2659.91 1306,-2649.91 1302.5,-2659.91 1309.5,-2659.91"/>
</g>
<!-- Vertreter §164 -->
<g id="node4" class="node"><title>Vertreter §164</title>
<polygon fill="none" stroke="black" points="944,-2285 826,-2285 826,-2249 944,-2249 944,-2285"/>
<text text-anchor="middle" x="885" y="-2262.9" font-family="Times Roman,serif" font-size="14.00">Vertreter §164</text>
</g>
<!-- Willenserklärung&#45;&gt;Vertreter §164 -->
<g id="edge6" class="edge"><title>Willenserklärung&#45;&gt;Vertreter §164</title>
<path fill="none" stroke="black" d="M1207.95,-2460.86C1140.33,-2426.6 1049.09,-2378.26 972,-2330 953.021,-2318.12 932.707,-2303.52 916.485,-2291.37"/>
<polygon fill="black" stroke="black" points="918.493,-2288.5 908.403,-2285.27 914.274,-2294.09 918.493,-2288.5"/>
</g>
<!-- Anfechtung -->
<g id="node6" class="node"><title>Anfechtung</title>
<polygon fill="none" stroke="black" points="981,-2205 981,-2329 1179,-2329 1179,-2205 981,-2205"/>
<text text-anchor="middle" x="1080" y="-2296.4" font-family="Times Roman,serif" font-size="14.00"> Anfechtung: §142 Abs.1</text>
<polyline fill="none" stroke="black" points="981,-2288 1179,-2288 "/>
<text text-anchor="middle" x="1080" y="-2255.4" font-family="Times Roman,serif" font-size="14.00"> Irrtum §119</text>
<polyline fill="none" stroke="black" points="981,-2247 1179,-2247 "/>
<text text-anchor="middle" x="1080" y="-2213.9" font-family="Times Roman,serif" font-size="14.00"> Übermittlungsfehler §120</text>
</g>
<!-- Willenserklärung&#45;&gt;Anfechtung -->
<g id="edge10" class="edge"><title>Willenserklärung&#45;&gt;Anfechtung</title>
<path fill="none" stroke="black" d="M1207.86,-2403.91C1186.55,-2381.09 1164.52,-2357.5 1144.87,-2336.47"/>
<polygon fill="black" stroke="black" points="1147.41,-2334.06 1138.03,-2329.14 1142.3,-2338.84 1147.41,-2334.06"/>
</g>
<!-- Letter of Intent §133 + §157 -->
<g id="node8" class="node"><title>Letter of Intent §133 + §157</title>
<polygon fill="none" stroke="black" points="1415,-2285 1197,-2285 1197,-2249 1415,-2249 1415,-2285"/>
<text text-anchor="middle" x="1306" y="-2262.9" font-family="Times Roman,serif" font-size="14.00">Letter of Intent §133 + §157</text>
</g>
<!-- Willenserklärung&#45;&gt;Letter of Intent §133 + §157 -->
<g id="edge18" class="edge"><title>Willenserklärung&#45;&gt;Letter of Intent §133 + §157</title>
<path fill="none" stroke="black" stroke-dasharray="5,2" d="M1299.33,-2368.23C1299.56,-2340.59 1300.27,-2314.36 1301.46,-2295.53"/>
<polygon fill="black" stroke="black" points="1304.96,-2295.58 1302.21,-2285.34 1297.98,-2295.06 1304.96,-2295.58"/>
</g>
<!-- Wirksamwerden §130 -->
<g id="node12" class="node"><title>Wirksamwerden §130</title>
<polygon fill="none" stroke="black" points="1601,-2285 1433,-2285 1433,-2249 1601,-2249 1601,-2285"/>
<text text-anchor="middle" x="1517" y="-2262.9" font-family="Times Roman,serif" font-size="14.00">Wirksamwerden §130</text>
</g>
<!-- Willenserklärung&#45;&gt;Wirksamwerden §130 -->
<g id="edge22" class="edge"><title>Willenserklärung&#45;&gt;Wirksamwerden §130</title>
<path fill="none" stroke="black" stroke-width="2" d="M1404.09,-2396.5C1437.88,-2357.74 1472.7,-2317.81 1494.57,-2292.73"/>
<polygon fill="black" stroke="black" points="1497.26,-2294.96 1501.19,-2285.13 1491.98,-2290.36 1497.26,-2294.96"/>
</g>
<!-- Vertreter ohne Vertretungvollmacht §177 -->
<g id="node5" class="node"><title>Vertreter ohne Vertretungvollmacht §177</title>
<polygon fill="none" stroke="black" points="999,-2166 695,-2166 695,-2130 999,-2130 999,-2166"/>
<text text-anchor="middle" x="847" y="-2143.9" font-family="Times Roman,serif" font-size="14.00">Vertreter ohne Vertretungvollmacht §177</text>
</g>
<!-- Vertreter §164&#45;&gt;Vertreter ohne Vertretungvollmacht §177 -->
<g id="edge8" class="edge"><title>Vertreter §164&#45;&gt;Vertreter ohne Vertretungvollmacht §177</title>
<path fill="none" stroke="black" d="M879.229,-2248.93C873.035,-2229.53 863.118,-2198.47 855.919,-2175.93"/>
<polygon fill="black" stroke="black" points="859.202,-2174.71 852.826,-2166.24 852.534,-2176.83 859.202,-2174.71"/>
</g>
<!-- Schadensersatz §122 -->
<g id="node7" class="node"><title>Schadensersatz §122</title>
<polygon fill="none" stroke="black" points="1181,-2166 1017,-2166 1017,-2130 1181,-2130 1181,-2166"/>
<text text-anchor="middle" x="1099" y="-2143.9" font-family="Times Roman,serif" font-size="14.00">Schadensersatz §122</text>
</g>
<!-- Anfechtung&#45;&gt;Schadensersatz §122 -->
<g id="edge12" class="edge"><title>Anfechtung&#45;&gt;Schadensersatz §122</title>
<path fill="none" stroke="black" d="M1089.95,-2204.71C1091.55,-2194.64 1093.15,-2184.67 1094.53,-2175.97"/>
<polygon fill="black" stroke="black" points="1098,-2176.48 1096.12,-2166.06 1091.08,-2175.38 1098,-2176.48"/>
</g>
<!-- Letter of Intent §133 + §157&#45;&gt;Willenserklärung -->
<g id="edge20" class="edge"><title>Letter of Intent §133 + §157&#45;&gt;Willenserklärung</title>
<path fill="none" stroke="black" stroke-dasharray="5,2" d="M1309.79,-2285.34C1311.27,-2302.21 1312.19,-2328.98 1312.56,-2358.23"/>
<polygon fill="black" stroke="black" points="1309.07,-2358.26 1312.67,-2368.23 1316.06,-2358.19 1309.07,-2358.26"/>
</g>
<!-- Vertragsanbahnung §311 Abs\.2 -->
<g id="node9" class="node"><title>Vertragsanbahnung §311 Abs\.2</title>
<polygon fill="none" stroke="black" points="1634,-2166 1400,-2166 1400,-2130 1634,-2130 1634,-2166"/>
<text text-anchor="middle" x="1517" y="-2143.9" font-family="Times Roman,serif" font-size="14.00">Vertragsanbahnung §311 Abs.2</text>
</g>
<!-- Pflichten §241 Abs\.2 -->
<g id="node10" class="node"><title>Pflichten §241 Abs\.2</title>
<polygon fill="none" stroke="black" points="1277,-2047 1119,-2047 1119,-2011 1277,-2011 1277,-2047"/>
<text text-anchor="middle" x="1198" y="-2024.9" font-family="Times Roman,serif" font-size="14.00">Pflichten §241 Abs.2</text>
</g>
<!-- Vertragsanbahnung §311 Abs\.2&#45;&gt;Pflichten §241 Abs\.2 -->
<g id="edge14" class="edge"><title>Vertragsanbahnung §311 Abs\.2&#45;&gt;Pflichten §241 Abs\.2</title>
<path fill="none" stroke="black" d="M1468.55,-2129.93C1411.47,-2108.63 1316.73,-2073.29 1255.85,-2050.58"/>
<polygon fill="black" stroke="black" points="1256.97,-2047.26 1246.38,-2047.05 1254.53,-2053.82 1256.97,-2047.26"/>
</g>
<!-- Antrag -->
<g id="node13" class="node"><title>Antrag</title>
<polygon fill="none" stroke="black" points="1637.5,-1967 1637.5,-2091 1790.5,-2091 1790.5,-1967 1637.5,-1967"/>
<text text-anchor="middle" x="1714" y="-2058.4" font-family="Times Roman,serif" font-size="14.00"> Antrag:</text>
<polyline fill="none" stroke="black" points="1637.5,-2050 1790.5,-2050 "/>
<text text-anchor="middle" x="1714" y="-2017.4" font-family="Times Roman,serif" font-size="14.00"> Bindung §145</text>
<polyline fill="none" stroke="black" points="1637.5,-2009 1790.5,-2009 "/>
<text text-anchor="middle" x="1714" y="-1975.9" font-family="Times Roman,serif" font-size="14.00"> Annahmefrist §148</text>
</g>
<!-- Vertragsanbahnung §311 Abs\.2&#45;&gt;Antrag -->
<g id="edge26" class="edge"><title>Vertragsanbahnung §311 Abs\.2&#45;&gt;Antrag</title>
<path fill="none" stroke="black" stroke-width="2" d="M1546.92,-2129.93C1568.77,-2116.73 1599.55,-2098.14 1628.75,-2080.5"/>
<polygon fill="black" stroke="black" points="1630.59,-2083.47 1637.34,-2075.31 1626.97,-2077.48 1630.59,-2083.47"/>
</g>
<!-- Schadensersatz §280 Abs\.1 Satz 1 -->
<g id="node11" class="node"><title>Schadensersatz §280 Abs\.1 Satz 1</title>
<polygon fill="none" stroke="black" points="961,-1822 705,-1822 705,-1786 961,-1786 961,-1822"/>
<text text-anchor="middle" x="833" y="-1799.9" font-family="Times Roman,serif" font-size="14.00">Schadensersatz §280 Abs.1 Satz 1</text>
</g>
<!-- Pflichten §241 Abs\.2&#45;&gt;Schadensersatz §280 Abs\.1 Satz 1 -->
<g id="edge16" class="edge"><title>Pflichten §241 Abs\.2&#45;&gt;Schadensersatz §280 Abs\.1 Satz 1</title>
<path fill="none" stroke="black" d="M1144.88,-2010.98C1097.06,-1993.5 1025.9,-1964.33 970,-1928 926.177,-1899.52 882.647,-1857.07 856.785,-1829.96"/>
<polygon fill="black" stroke="black" points="859.068,-1827.28 849.659,-1822.41 853.977,-1832.09 859.068,-1827.28"/>
</g>
<!-- Wirksamwerden §130&#45;&gt;Vertragsanbahnung §311 Abs\.2 -->
<g id="edge24" class="edge"><title>Wirksamwerden §130&#45;&gt;Vertragsanbahnung §311 Abs\.2</title>
<path fill="none" stroke="black" stroke-width="2" d="M1517,-2248.93C1517,-2229.71 1517,-2199.03 1517,-2176.54"/>
<polygon fill="black" stroke="black" points="1520.5,-2176.24 1517,-2166.24 1513.5,-2176.24 1520.5,-2176.24"/>
</g>
<!-- Vertragsannahme -->
<g id="node14" class="node"><title>Vertragsannahme</title>
<polygon fill="none" stroke="black" points="979,-1680.5 979,-1927.5 1267,-1927.5 1267,-1680.5 979,-1680.5"/>
<text text-anchor="middle" x="1123" y="-1894.9" font-family="Times Roman,serif" font-size="14.00"> Vertragsannahme:</text>
<polyline fill="none" stroke="black" points="979,-1886.5 1267,-1886.5 "/>
<text text-anchor="middle" x="1123" y="-1853.9" font-family="Times Roman,serif" font-size="14.00"> Anwesenheit §147 Abs.1</text>
<polyline fill="none" stroke="black" points="979,-1845.5 1267,-1845.5 "/>
<text text-anchor="middle" x="1123" y="-1812.9" font-family="Times Roman,serif" font-size="14.00"> Abwesenheit §147 Abs.2</text>
<polyline fill="none" stroke="black" points="979,-1804.5 1267,-1804.5 "/>
<text text-anchor="middle" x="1123" y="-1771.9" font-family="Times Roman,serif" font-size="14.00"> verspäteter Zugang §149</text>
<polyline fill="none" stroke="black" points="979,-1763.5 1267,-1763.5 "/>
<text text-anchor="middle" x="1123" y="-1730.9" font-family="Times Roman,serif" font-size="14.00"> gleichwertige Annahmehandlung §151</text>
<polyline fill="none" stroke="black" points="979,-1722.5 1267,-1722.5 "/>
<text text-anchor="middle" x="1123" y="-1689.4" font-family="Times Roman,serif" font-size="14.00"> Versteigerung §156</text>
</g>
<!-- Antrag&#45;&gt;Vertragsannahme -->
<g id="edge28" class="edge"><title>Antrag&#45;&gt;Vertragsannahme</title>
<path fill="none" stroke="black" stroke-width="2" d="M1637.29,-2021.92C1549.2,-2011.5 1401.77,-1986.97 1276.62,-1928.03"/>
<polygon fill="black" stroke="black" points="1277.79,-1924.71 1267.26,-1923.54 1274.76,-1931.02 1277.79,-1924.71"/>
</g>
<!-- AGB -->
<g id="node15" class="node"><title>AGB</title>
<polygon fill="none" stroke="black" points="1285,-1721.5 1285,-1886.5 1761,-1886.5 1761,-1721.5 1285,-1721.5"/>
<text text-anchor="middle" x="1523" y="-1853.9" font-family="Times Roman,serif" font-size="14.00"> AGB:</text>
<polyline fill="none" stroke="black" points="1285,-1845.5 1761,-1845.5 "/>
<text text-anchor="middle" x="1523" y="-1812.9" font-family="Times Roman,serif" font-size="14.00"> Nutzung §305 + §305a</text>
<polyline fill="none" stroke="black" points="1285,-1804.5 1761,-1804.5 "/>
<text text-anchor="middle" x="1523" y="-1771.9" font-family="Times Roman,serif" font-size="14.00"> Unwirksamkeit §305b+c + §306 + §306a + §307 + §308 + §309</text>
<polyline fill="none" stroke="black" points="1285,-1763.5 1761,-1763.5 "/>
<text text-anchor="middle" x="1523" y="-1730.4" font-family="Times Roman,serif" font-size="14.00"> Anwendungsbereich §310</text>
</g>
<!-- Antrag&#45;&gt;AGB -->
<g id="edge42" class="edge"><title>Antrag&#45;&gt;AGB</title>
<path fill="none" stroke="black" d="M1655.2,-1966.92C1635.55,-1944.5 1613.49,-1918.72 1593.08,-1894.37"/>
<polygon fill="black" stroke="black" points="1595.62,-1891.95 1586.52,-1886.52 1590.25,-1896.44 1595.62,-1891.95"/>
</g>
<!-- abändernde Annahme §150 Abs\.2 -->
<g id="node46" class="node"><title>abändernde Annahme §150 Abs\.2</title>
<polygon fill="none" stroke="black" points="2029,-1822 1779,-1822 1779,-1786 2029,-1786 2029,-1822"/>
<text text-anchor="middle" x="1904" y="-1799.9" font-family="Times Roman,serif" font-size="14.00">abändernde Annahme §150 Abs.2</text>
</g>
<!-- Antrag&#45;&gt;abändernde Annahme §150 Abs\.2 -->
<g id="edge30" class="edge"><title>Antrag&#45;&gt;abändernde Annahme §150 Abs\.2</title>
<path fill="none" stroke="black" d="M1760.31,-1966.92C1797.31,-1921.64 1847.7,-1862.63 1878.01,-1829.48"/>
<polygon fill="black" stroke="black" points="1880.68,-1831.75 1884.9,-1822.03 1875.54,-1827 1880.68,-1831.75"/>
</g>
<!-- Erlöschen §146 -->
<g id="node47" class="node"><title>Erlöschen §146</title>
<polygon fill="none" stroke="black" points="2169,-1822 2047,-1822 2047,-1786 2169,-1786 2169,-1822"/>
<text text-anchor="middle" x="2108" y="-1799.9" font-family="Times Roman,serif" font-size="14.00">Erlöschen §146</text>
</g>
<!-- Antrag&#45;&gt;Erlöschen §146 -->
<g id="edge34" class="edge"><title>Antrag&#45;&gt;Erlöschen §146</title>
<path fill="none" stroke="black" d="M1790.62,-2021.3C1861.49,-2010.71 1966.39,-1985.85 2038,-1928 2069.17,-1902.82 2088.93,-1859.81 2099.24,-1831.65"/>
<polygon fill="black" stroke="black" points="2102.61,-1832.6 2102.61,-1822.01 2096,-1830.29 2102.61,-1832.6"/>
</g>
<!-- Dissens -->
<g id="node16" class="node"><title>Dissens</title>
<polygon fill="none" stroke="black" points="1041.5,-1517 1041.5,-1641 1180.5,-1641 1180.5,-1517 1041.5,-1517"/>
<text text-anchor="middle" x="1111" y="-1608.4" font-family="Times Roman,serif" font-size="14.00"> Dissens:</text>
<polyline fill="none" stroke="black" points="1041.5,-1600 1180.5,-1600 "/>
<text text-anchor="middle" x="1111" y="-1567.4" font-family="Times Roman,serif" font-size="14.00"> offener §154</text>
<polyline fill="none" stroke="black" points="1041.5,-1559 1180.5,-1559 "/>
<text text-anchor="middle" x="1111" y="-1525.9" font-family="Times Roman,serif" font-size="14.00"> versteckter §154</text>
</g>
<!-- Vertragsannahme&#45;&gt;Dissens -->
<g id="edge40" class="edge"><title>Vertragsannahme&#45;&gt;Dissens</title>
<path fill="none" stroke="black" d="M1116.4,-1680.31C1115.87,-1670.34 1115.35,-1660.48 1114.84,-1651.06"/>
<polygon fill="black" stroke="black" points="1118.34,-1650.83 1114.31,-1641.03 1111.35,-1651.2 1118.34,-1650.83"/>
</g>
<!-- Vertrag -->
<g id="node17" class="node"><title>Vertrag</title>
<polygon fill="none" stroke="black" points="1266,-1597 1198,-1597 1198,-1561 1266,-1561 1266,-1597"/>
<text text-anchor="middle" x="1232" y="-1574.9" font-family="Times Roman,serif" font-size="14.00">Vertrag</text>
</g>
<!-- Vertragsannahme&#45;&gt;Vertrag -->
<g id="edge46" class="edge"><title>Vertragsannahme&#45;&gt;Vertrag</title>
<path fill="none" stroke="black" stroke-width="2" d="M1182.92,-1680.31C1196.4,-1652.48 1209.43,-1625.58 1218.68,-1606.5"/>
<polygon fill="black" stroke="black" points="1221.94,-1607.8 1223.15,-1597.27 1215.64,-1604.74 1221.94,-1607.8"/>
</g>
<!-- AGB&#45;&gt;Antrag -->
<g id="edge44" class="edge"><title>AGB&#45;&gt;Antrag</title>
<path fill="none" stroke="black" d="M1599.58,-1886.52C1620.12,-1910.29 1641.85,-1935.99 1660.82,-1958.93"/>
<polygon fill="black" stroke="black" points="1658.35,-1961.43 1667.41,-1966.92 1663.75,-1956.98 1658.35,-1961.43"/>
</g>
<!-- allg\. Schuldverhältnis -->
<g id="node18" class="node"><title>allg\. Schuldverhältnis</title>
<polygon fill="none" stroke="black" points="362,-1435 362,-1477 578,-1477 578,-1435 362,-1435"/>
<text text-anchor="middle" x="470" y="-1443.9" font-family="Times Roman,serif" font-size="14.00"> Allg. Schuldverhältniss §311</text>
</g>
<!-- Vertrag&#45;&gt;allg\. Schuldverhältnis -->
<g id="edge48" class="edge"><title>Vertrag&#45;&gt;allg\. Schuldverhältnis</title>
<path fill="none" stroke="black" stroke-width="2" d="M1224.95,-1560.98C1218.13,-1546.18 1206.28,-1526.07 1189,-1516 1138.46,-1486.55 778.914,-1468.14 588.18,-1460.33"/>
<polygon fill="black" stroke="black" points="588.24,-1456.83 578.106,-1459.92 587.956,-1463.82 588.24,-1456.83"/>
</g>
<!-- spez\. Schuldverhältnis -->
<g id="node26" class="node"><title>spez\. Schuldverhältnis</title>
<polygon fill="none" stroke="black" points="1498,-1474 1326,-1474 1326,-1438 1498,-1438 1498,-1474"/>
<text text-anchor="middle" x="1412" y="-1451.9" font-family="Times Roman,serif" font-size="14.00">spez. Schuldverhältnis</text>
</g>
<!-- Vertrag&#45;&gt;spez\. Schuldverhältnis -->
<g id="edge50" class="edge"><title>Vertrag&#45;&gt;spez\. Schuldverhältnis</title>
<path fill="none" stroke="black" stroke-width="2" d="M1258.56,-1560.85C1290.02,-1539.35 1342.53,-1503.47 1377.21,-1479.77"/>
<polygon fill="black" stroke="black" points="1379.34,-1482.55 1385.62,-1474.02 1375.39,-1476.78 1379.34,-1482.55"/>
</g>
<!-- Erfüllung -->
<g id="node19" class="node"><title>Erfüllung</title>
<polygon fill="none" stroke="black" points="0,-1189 0,-1395 218,-1395 218,-1189 0,-1189"/>
<text text-anchor="middle" x="109" y="-1362.4" font-family="Times Roman,serif" font-size="14.00"> Erfüllung:</text>
<polyline fill="none" stroke="black" points="0,-1354 218,-1354 "/>
<text text-anchor="middle" x="109" y="-1321.4" font-family="Times Roman,serif" font-size="14.00"> durch Leistung §362 + §364</text>
<polyline fill="none" stroke="black" points="0,-1313 218,-1313 "/>
<text text-anchor="middle" x="109" y="-1280.4" font-family="Times Roman,serif" font-size="14.00"> Hinterlegung §372ff</text>
<polyline fill="none" stroke="black" points="0,-1272 218,-1272 "/>
<text text-anchor="middle" x="109" y="-1239.4" font-family="Times Roman,serif" font-size="14.00"> Aufrechnung §387ff</text>
<polyline fill="none" stroke="black" points="0,-1231 218,-1231 "/>
<text text-anchor="middle" x="109" y="-1197.9" font-family="Times Roman,serif" font-size="14.00"> Erlass §397</text>
</g>
<!-- allg\. Schuldverhältnis&#45;&gt;Erfüllung -->
<g id="edge54" class="edge"><title>allg\. Schuldverhältnis&#45;&gt;Erfüllung</title>
<path fill="none" stroke="black" stroke-width="2" d="M361.946,-1440.85C320.965,-1432.39 274.58,-1419.45 227.454,-1395.88"/>
<polygon fill="black" stroke="black" points="228.828,-1392.66 218.334,-1391.19 225.626,-1398.88 228.828,-1392.66"/>
</g>
<!-- Schuldner -->
<g id="node20" class="node"><title>Schuldner</title>
<polygon fill="none" stroke="black" points="235.5,-1189 235.5,-1395 484.5,-1395 484.5,-1189 235.5,-1189"/>
<text text-anchor="middle" x="360" y="-1362.4" font-family="Times Roman,serif" font-size="14.00"> Schuldner:</text>
<polyline fill="none" stroke="black" points="235.5,-1354 484.5,-1354 "/>
<text text-anchor="middle" x="360" y="-1321.4" font-family="Times Roman,serif" font-size="14.00"> Hauptleistungspflicht §241 Abs.1</text>
<polyline fill="none" stroke="black" points="235.5,-1313 484.5,-1313 "/>
<text text-anchor="middle" x="360" y="-1280.4" font-family="Times Roman,serif" font-size="14.00"> Schutzpflicht §241 Abs.2</text>
<polyline fill="none" stroke="black" points="235.5,-1272 484.5,-1272 "/>
<text text-anchor="middle" x="360" y="-1239.4" font-family="Times Roman,serif" font-size="14.00"> Leistungsort §269</text>
<polyline fill="none" stroke="black" points="235.5,-1231 484.5,-1231 "/>
<text text-anchor="middle" x="360" y="-1197.9" font-family="Times Roman,serif" font-size="14.00"> Zahlungsort §270</text>
</g>
<!-- allg\. Schuldverhältnis&#45;&gt;Schuldner -->
<g id="edge62" class="edge"><title>allg\. Schuldverhältnis&#45;&gt;Schuldner</title>
<path fill="none" stroke="black" stroke-width="2" d="M455.845,-1434.9C450.055,-1426.26 442.881,-1415.57 435.084,-1403.94"/>
<polygon fill="black" stroke="black" points="437.783,-1401.68 429.306,-1395.33 431.97,-1405.58 437.783,-1401.68"/>
</g>
<!-- Gläubiger -->
<g id="node23" class="node"><title>Gläubiger</title>
<polygon fill="none" stroke="black" points="502,-1230 502,-1354 792,-1354 792,-1230 502,-1230"/>
<text text-anchor="middle" x="647" y="-1321.4" font-family="Times Roman,serif" font-size="14.00"> Gläubiger:</text>
<polyline fill="none" stroke="black" points="502,-1313 792,-1313 "/>
<text text-anchor="middle" x="647" y="-1280.4" font-family="Times Roman,serif" font-size="14.00"> Annahmeverzug §293</text>
<polyline fill="none" stroke="black" points="502,-1272 792,-1272 "/>
<text text-anchor="middle" x="647" y="-1238.9" font-family="Times Roman,serif" font-size="14.00"> Wirkungen des Gläubigerverzugs §300</text>
</g>
<!-- allg\. Schuldverhältnis&#45;&gt;Gläubiger -->
<g id="edge52" class="edge"><title>allg\. Schuldverhältnis&#45;&gt;Gläubiger</title>
<path fill="none" stroke="black" stroke-width="2" d="M492.777,-1434.9C513.005,-1416.15 543.726,-1387.69 572.439,-1361.08"/>
<polygon fill="black" stroke="black" points="575.123,-1363.37 580.08,-1354.01 570.366,-1358.23 575.123,-1363.37"/>
</g>
<!-- Pflichtverletzung -->
<g id="node49" class="node"><title>Pflichtverletzung</title>
<polygon fill="none" stroke="black" points="347,-1085 213,-1085 213,-1049 347,-1049 347,-1085"/>
<text text-anchor="middle" x="280" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Pflichtverletzung</text>
</g>
<!-- Schuldner&#45;&gt;Pflichtverletzung -->
<g id="edge64" class="edge"><title>Schuldner&#45;&gt;Pflichtverletzung</title>
<path fill="none" stroke="black" d="M323.278,-1188.72C311.041,-1154.3 298.392,-1118.73 289.954,-1094.99"/>
<polygon fill="black" stroke="black" points="293.147,-1093.53 286.499,-1085.28 286.551,-1095.87 293.147,-1093.53"/>
</g>
<!-- Verantwortlichkeit -->
<g id="node21" class="node"><title>Verantwortlichkeit</title>
<polygon fill="none" stroke="black" points="70.5,-451.5 70.5,-616.5 479.5,-616.5 479.5,-451.5 70.5,-451.5"/>
<text text-anchor="middle" x="275" y="-583.9" font-family="Times Roman,serif" font-size="14.00"> Vertretenmüssen:</text>
<polyline fill="none" stroke="black" points="70.5,-575.5 479.5,-575.5 "/>
<text text-anchor="middle" x="275" y="-542.9" font-family="Times Roman,serif" font-size="14.00"> Verantwortlichkeit §276</text>
<polyline fill="none" stroke="black" points="70.5,-534.5 479.5,-534.5 "/>
<text text-anchor="middle" x="275" y="-501.9" font-family="Times Roman,serif" font-size="14.00"> Sorgfalt §277</text>
<polyline fill="none" stroke="black" points="70.5,-493.5 479.5,-493.5 "/>
<text text-anchor="middle" x="275" y="-460.4" font-family="Times Roman,serif" font-size="14.00"> Verantw. für Dritte/Verrichtungsgeh.&#45;Haft. §278 + §831</text>
</g>
<!-- Schadensersatz -->
<g id="node22" class="node"><title>Schadensersatz</title>
<polygon fill="none" stroke="black" points="297.5,-1 297.5,-289 600.5,-289 600.5,-1 297.5,-1"/>
<text text-anchor="middle" x="449" y="-256.4" font-family="Times Roman,serif" font-size="14.00"> Schadensersatz:</text>
<polyline fill="none" stroke="black" points="297.5,-248 600.5,-248 "/>
<text text-anchor="middle" x="449" y="-215.4" font-family="Times Roman,serif" font-size="14.00"> wegen Pflichtverletzung §280 Abs.1</text>
<polyline fill="none" stroke="black" points="297.5,-207 600.5,-207 "/>
<text text-anchor="middle" x="449" y="-174.4" font-family="Times Roman,serif" font-size="14.00"> statt der Leistung §281</text>
<polyline fill="none" stroke="black" points="297.5,-166 600.5,-166 "/>
<text text-anchor="middle" x="449" y="-133.4" font-family="Times Roman,serif" font-size="14.00"> Schutzpflichtverletzung §282</text>
<polyline fill="none" stroke="black" points="297.5,-125 600.5,-125 "/>
<text text-anchor="middle" x="449" y="-92.4" font-family="Times Roman,serif" font-size="14.00"> bei Ausschluss der Leistungspflicht §283</text>
<polyline fill="none" stroke="black" points="297.5,-84 600.5,-84 "/>
<text text-anchor="middle" x="449" y="-51.4" font-family="Times Roman,serif" font-size="14.00"> Ersatz vergeblicher Aufwendungen §284</text>
<polyline fill="none" stroke="black" points="297.5,-43 600.5,-43 "/>
<text text-anchor="middle" x="449" y="-9.9" font-family="Times Roman,serif" font-size="14.00"> bei Verzug §286 + §287 + §288</text>
</g>
<!-- Verantwortlichkeit&#45;&gt;Schadensersatz -->
<g id="edge68" class="edge"><title>Verantwortlichkeit&#45;&gt;Schadensersatz</title>
<path fill="none" stroke="black" d="M312.114,-451.027C331.981,-406.612 357.089,-350.479 380.361,-298.451"/>
<polygon fill="black" stroke="black" points="383.644,-299.685 384.532,-289.127 377.254,-296.826 383.644,-299.685"/>
</g>
<!-- Rücktritt -->
<g id="node24" class="node"><title>Rücktritt</title>
<polygon fill="none" stroke="black" points="402,-759 402,-965 614,-965 614,-759 402,-759"/>
<text text-anchor="middle" x="508" y="-932.4" font-family="Times Roman,serif" font-size="14.00"> Rücktritt:</text>
<polyline fill="none" stroke="black" points="402,-924 614,-924 "/>
<text text-anchor="middle" x="508" y="-891.4" font-family="Times Roman,serif" font-size="14.00"> keine/falsche Leistung §323</text>
<polyline fill="none" stroke="black" points="402,-883 614,-883 "/>
<text text-anchor="middle" x="508" y="-850.4" font-family="Times Roman,serif" font-size="14.00"> Pflichtverletzung §324</text>
<polyline fill="none" stroke="black" points="402,-842 614,-842 "/>
<text text-anchor="middle" x="508" y="-809.4" font-family="Times Roman,serif" font-size="14.00"> Wirkungen §346</text>
<polyline fill="none" stroke="black" points="402,-801 614,-801 "/>
<text text-anchor="middle" x="508" y="-767.9" font-family="Times Roman,serif" font-size="14.00"> Erklärung §349</text>
</g>
<!-- Gläubiger&#45;&gt;Rücktritt -->
<g id="edge56" class="edge"><title>Gläubiger&#45;&gt;Rücktritt</title>
<path fill="none" stroke="black" d="M578.275,-1229.89C557.411,-1206.97 536.883,-1179.38 525,-1150 502.855,-1095.25 497.503,-1029.84 498.172,-975.2"/>
<polygon fill="black" stroke="black" points="501.673,-975.193 498.365,-965.128 494.674,-975.059 501.673,-975.193"/>
</g>
<!-- Verbraucher -->
<g id="node25" class="node"><title>Verbraucher</title>
<polygon fill="none" stroke="black" points="533.5,-984.5 533.5,-1149.5 786.5,-1149.5 786.5,-984.5 533.5,-984.5"/>
<text text-anchor="middle" x="660" y="-1116.9" font-family="Times Roman,serif" font-size="14.00"> Verbraucher:</text>
<polyline fill="none" stroke="black" points="533.5,-1108.5 786.5,-1108.5 "/>
<text text-anchor="middle" x="660" y="-1075.9" font-family="Times Roman,serif" font-size="14.00"> Widerruf §355</text>
<polyline fill="none" stroke="black" points="533.5,-1067.5 786.5,-1067.5 "/>
<text text-anchor="middle" x="660" y="-1034.9" font-family="Times Roman,serif" font-size="14.00"> Rückgabe §356</text>
<polyline fill="none" stroke="black" points="533.5,-1026.5 786.5,-1026.5 "/>
<text text-anchor="middle" x="660" y="-993.4" font-family="Times Roman,serif" font-size="14.00"> Rechtsfolgen Widerr./Rückg. §357</text>
</g>
<!-- Gläubiger&#45;&gt;Verbraucher -->
<g id="edge58" class="edge"><title>Gläubiger&#45;&gt;Verbraucher</title>
<path fill="none" stroke="black" d="M650.587,-1229.92C651.843,-1208.18 653.282,-1183.28 654.65,-1159.59"/>
<polygon fill="black" stroke="black" points="658.149,-1159.71 655.232,-1149.52 651.161,-1159.3 658.149,-1159.71"/>
</g>
<!-- Rücktritt&#45;&gt;Schadensersatz -->
<g id="edge60" class="edge"><title>Rücktritt&#45;&gt;Schadensersatz</title>
<path fill="none" stroke="black" d="M509.392,-758.957C509.623,-651.1 506.53,-477.029 488,-328 486.84,-318.669 485.443,-309.109 483.879,-299.49"/>
<polygon fill="black" stroke="black" points="487.301,-298.734 482.191,-289.453 480.398,-299.895 487.301,-298.734"/>
<text text-anchor="middle" x="527.5" y="-529.9" font-family="Times Roman,serif" font-size="14.00">§325</text>
</g>
<!-- Kaufvertrag -->
<g id="node27" class="node"><title>Kaufvertrag</title>
<polygon fill="none" stroke="black" points="970.5,-1221.5 970.5,-1362.5 1145.5,-1362.5 1145.5,-1221.5 970.5,-1221.5"/>
<text text-anchor="middle" x="1058" y="-1329.9" font-family="Times Roman,serif" font-size="14.00"> Kaufvertrag:</text>
<polyline fill="none" stroke="black" points="970.5,-1321.5 1145.5,-1321.5 "/>
<text text-anchor="middle" x="1058" y="-1288.9" font-family="Times Roman,serif" font-size="14.00"> Pflichten §433</text>
<polyline fill="none" stroke="black" points="970.5,-1280.5 1145.5,-1280.5 "/>
<text text-anchor="middle" x="1058" y="-1247.4" font-family="Times Roman,serif" font-size="14.00"> Sache §90</text>
<text text-anchor="middle" x="1058" y="-1230.4" font-family="Times Roman,serif" font-size="14.00"> Verbrauchsgüter §474</text>
</g>
<!-- spez\. Schuldverhältnis&#45;&gt;Kaufvertrag -->
<g id="edge70" class="edge"><title>spez\. Schuldverhältnis&#45;&gt;Kaufvertrag</title>
<path fill="none" stroke="black" stroke-width="2" d="M1373.1,-1437.98C1321,-1413.84 1226.78,-1370.19 1154.9,-1336.89"/>
<polygon fill="black" stroke="black" points="1156.35,-1333.71 1145.81,-1332.68 1153.41,-1340.06 1156.35,-1333.71"/>
</g>
<!-- Werkvertrag -->
<g id="node33" class="node"><title>Werkvertrag</title>
<polygon fill="none" stroke="black" points="1318,-1250.5 1318,-1333.5 1506,-1333.5 1506,-1250.5 1318,-1250.5"/>
<text text-anchor="middle" x="1412" y="-1300.9" font-family="Times Roman,serif" font-size="14.00"> Werkvertrag:</text>
<polyline fill="none" stroke="black" points="1318,-1292.5 1506,-1292.5 "/>
<text text-anchor="middle" x="1412" y="-1259.4" font-family="Times Roman,serif" font-size="14.00"> Individualsoftware §651</text>
</g>
<!-- spez\. Schuldverhältnis&#45;&gt;Werkvertrag -->
<g id="edge82" class="edge"><title>spez\. Schuldverhältnis&#45;&gt;Werkvertrag</title>
<path fill="none" stroke="black" stroke-width="2" d="M1412,-1437.82C1412,-1415.32 1412,-1376.04 1412,-1343.92"/>
<polygon fill="black" stroke="black" points="1415.5,-1343.77 1412,-1333.77 1408.5,-1343.77 1415.5,-1343.77"/>
</g>
<!-- Dienstvertrag -->
<g id="node40" class="node"><title>Dienstvertrag</title>
<polygon fill="none" stroke="black" points="1711,-1310 1599,-1310 1599,-1274 1711,-1274 1711,-1310"/>
<text text-anchor="middle" x="1655" y="-1287.9" font-family="Times Roman,serif" font-size="14.00">Dienstvertrag</text>
</g>
<!-- spez\. Schuldverhältnis&#45;&gt;Dienstvertrag -->
<g id="edge96" class="edge"><title>spez\. Schuldverhältnis&#45;&gt;Dienstvertrag</title>
<path fill="none" stroke="black" stroke-width="2" d="M1445.04,-1437.99C1465.53,-1426.53 1492.2,-1411.04 1515,-1396 1553.71,-1370.46 1596.21,-1338.26 1624.11,-1316.5"/>
<polygon fill="black" stroke="black" points="1626.57,-1319.03 1632.28,-1310.11 1622.25,-1313.52 1626.57,-1319.03"/>
</g>
<!-- Mietvertrag -->
<g id="node42" class="node"><title>Mietvertrag</title>
<polygon fill="none" stroke="black" points="1797,-1250.5 1797,-1333.5 1959,-1333.5 1959,-1250.5 1797,-1250.5"/>
<text text-anchor="middle" x="1878" y="-1300.9" font-family="Times Roman,serif" font-size="14.00"> Mietvertrag:</text>
<polyline fill="none" stroke="black" points="1797,-1292.5 1959,-1292.5 "/>
<text text-anchor="middle" x="1878" y="-1259.4" font-family="Times Roman,serif" font-size="14.00"> Hauptpflichten §535</text>
</g>
<!-- spez\. Schuldverhältnis&#45;&gt;Mietvertrag -->
<g id="edge100" class="edge"><title>spez\. Schuldverhältnis&#45;&gt;Mietvertrag</title>
<path fill="none" stroke="black" stroke-width="2" d="M1498.22,-1448.28C1561.44,-1440.48 1648.37,-1425.21 1720,-1396 1754.59,-1381.89 1789.65,-1359.78 1817.92,-1339.57"/>
<polygon fill="black" stroke="black" points="1820.04,-1342.35 1826.08,-1333.65 1815.93,-1336.69 1820.04,-1342.35"/>
</g>
<!-- Käufer -->
<g id="node28" class="node"><title>Käufer</title>
<polygon fill="none" stroke="black" points="866,-1085 804,-1085 804,-1049 866,-1049 866,-1085"/>
<text text-anchor="middle" x="835" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Käufer</text>
</g>
<!-- Kaufvertrag&#45;&gt;Käufer -->
<g id="edge72" class="edge"><title>Kaufvertrag&#45;&gt;Käufer</title>
<path fill="none" stroke="black" d="M970.282,-1236.68C937.445,-1212.9 901.676,-1182.99 875,-1150 861.632,-1133.47 851.362,-1111.73 844.578,-1094.65"/>
<polygon fill="black" stroke="black" points="847.812,-1093.31 840.989,-1085.2 841.269,-1095.79 847.812,-1093.31"/>
</g>
<!-- Gefahrenübergang §446f + §474 -->
<g id="node30" class="node"><title>Gefahrenübergang §446f + §474</title>
<polygon fill="none" stroke="black" points="1128,-1085 884,-1085 884,-1049 1128,-1049 1128,-1085"/>
<text text-anchor="middle" x="1006" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Gefahrenübergang §446f + §474</text>
</g>
<!-- Kaufvertrag&#45;&gt;Gefahrenübergang §446f + §474 -->
<g id="edge78" class="edge"><title>Kaufvertrag&#45;&gt;Gefahrenübergang §446f + §474</title>
<path fill="none" stroke="black" d="M1041.69,-1221.43C1031.79,-1178.58 1019.7,-1126.28 1012.44,-1094.85"/>
<polygon fill="black" stroke="black" points="1015.83,-1094 1010.17,-1085.04 1009.01,-1095.57 1015.83,-1094"/>
</g>
<!-- Verkäufer -->
<g id="node31" class="node"><title>Verkäufer</title>
<polygon fill="none" stroke="black" points="1230,-1085 1146,-1085 1146,-1049 1230,-1049 1230,-1085"/>
<text text-anchor="middle" x="1188" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Verkäufer</text>
</g>
<!-- Kaufvertrag&#45;&gt;Verkäufer -->
<g id="edge74" class="edge"><title>Kaufvertrag&#45;&gt;Verkäufer</title>
<path fill="none" stroke="black" d="M1098.78,-1221.43C1123.74,-1178.21 1154.28,-1125.37 1172.38,-1094.04"/>
<polygon fill="black" stroke="black" points="1175.6,-1095.45 1177.58,-1085.04 1169.54,-1091.95 1175.6,-1095.45"/>
</g>
<!-- Mängel -->
<g id="node29" class="node"><title>Mängel</title>
<polygon fill="none" stroke="black" points="691.5,-328.5 691.5,-739.5 970.5,-739.5 970.5,-328.5 691.5,-328.5"/>
<text text-anchor="middle" x="831" y="-706.9" font-family="Times Roman,serif" font-size="14.00"> Mängel:</text>
<polyline fill="none" stroke="black" points="691.5,-698.5 970.5,-698.5 "/>
<text text-anchor="middle" x="831" y="-665.9" font-family="Times Roman,serif" font-size="14.00"> Sachmangel §434</text>
<polyline fill="none" stroke="black" points="691.5,-657.5 970.5,-657.5 "/>
<text text-anchor="middle" x="831" y="-624.9" font-family="Times Roman,serif" font-size="14.00"> Rechtsmangel §435</text>
<polyline fill="none" stroke="black" points="691.5,-616.5 970.5,-616.5 "/>
<text text-anchor="middle" x="831" y="-583.9" font-family="Times Roman,serif" font-size="14.00"> Rechte des Käufers bei Mängeln §437</text>
<polyline fill="none" stroke="black" points="691.5,-575.5 970.5,-575.5 "/>
<text text-anchor="middle" x="831" y="-542.9" font-family="Times Roman,serif" font-size="14.00"> Verjährung §438</text>
<polyline fill="none" stroke="black" points="691.5,-534.5 970.5,-534.5 "/>
<text text-anchor="middle" x="831" y="-501.9" font-family="Times Roman,serif" font-size="14.00"> Nacherfüllung §439</text>
<polyline fill="none" stroke="black" points="691.5,-493.5 970.5,-493.5 "/>
<text text-anchor="middle" x="831" y="-460.9" font-family="Times Roman,serif" font-size="14.00"> keine Frist §440</text>
<polyline fill="none" stroke="black" points="691.5,-452.5 970.5,-452.5 "/>
<text text-anchor="middle" x="831" y="-419.9" font-family="Times Roman,serif" font-size="14.00"> Minderung §441</text>
<polyline fill="none" stroke="black" points="691.5,-411.5 970.5,-411.5 "/>
<text text-anchor="middle" x="831" y="-378.9" font-family="Times Roman,serif" font-size="14.00"> Kenntniss d. Käufers §442</text>
<polyline fill="none" stroke="black" points="691.5,-370.5 970.5,-370.5 "/>
<text text-anchor="middle" x="831" y="-337.4" font-family="Times Roman,serif" font-size="14.00"> Beweislastumkehr §476</text>
</g>
<!-- Käufer&#45;&gt;Mängel -->
<g id="edge76" class="edge"><title>Käufer&#45;&gt;Mängel</title>
<path fill="none" stroke="black" d="M834.865,-1048.96C834.509,-1001.52 833.512,-868.714 832.62,-749.861"/>
<polygon fill="black" stroke="black" points="836.117,-749.48 832.542,-739.507 829.118,-749.533 836.117,-749.48"/>
</g>
<!-- Regress §478 -->
<g id="node32" class="node"><title>Regress §478</title>
<polygon fill="none" stroke="black" points="1096,-552 988,-552 988,-516 1096,-516 1096,-552"/>
<text text-anchor="middle" x="1042" y="-529.9" font-family="Times Roman,serif" font-size="14.00">Regress §478</text>
</g>
<!-- Verkäufer&#45;&gt;Regress §478 -->
<g id="edge80" class="edge"><title>Verkäufer&#45;&gt;Regress §478</title>
<path fill="none" stroke="black" d="M1183.06,-1048.96C1161.53,-970.35 1075.8,-657.378 1049.63,-561.839"/>
<polygon fill="black" stroke="black" points="1052.96,-560.755 1046.94,-552.035 1046.21,-562.604 1052.96,-560.755"/>
</g>
<!-- Besteller -->
<g id="node34" class="node"><title>Besteller</title>
<polygon fill="none" stroke="black" points="1339,-1085 1263,-1085 1263,-1049 1339,-1049 1339,-1085"/>
<text text-anchor="middle" x="1301" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Besteller</text>
</g>
<!-- Werkvertrag&#45;&gt;Besteller -->
<g id="edge84" class="edge"><title>Werkvertrag&#45;&gt;Besteller</title>
<path fill="none" stroke="black" d="M1391.51,-1250.47C1369.05,-1204.93 1333.65,-1133.18 1314.46,-1094.27"/>
<polygon fill="black" stroke="black" points="1317.51,-1092.55 1309.94,-1085.13 1311.23,-1095.64 1317.51,-1092.55"/>
</g>
<!-- Unternehmer -->
<g id="node35" class="node"><title>Unternehmer</title>
<polygon fill="none" stroke="black" points="1467,-1085 1357,-1085 1357,-1049 1467,-1049 1467,-1085"/>
<text text-anchor="middle" x="1412" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Unternehmer</text>
</g>
<!-- Werkvertrag&#45;&gt;Unternehmer -->
<g id="edge86" class="edge"><title>Werkvertrag&#45;&gt;Unternehmer</title>
<path fill="none" stroke="black" d="M1412,-1250.47C1412,-1205.32 1412,-1134.39 1412,-1095.27"/>
<polygon fill="black" stroke="black" points="1415.5,-1095.13 1412,-1085.13 1408.5,-1095.13 1415.5,-1095.13"/>
</g>
<!-- Gefahrenübergang §644 -->
<g id="node36" class="node"><title>Gefahrenübergang §644</title>
<polygon fill="none" stroke="black" points="1669,-1085 1485,-1085 1485,-1049 1669,-1049 1669,-1085"/>
<text text-anchor="middle" x="1577" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Gefahrenübergang §644</text>
</g>
<!-- Werkvertrag&#45;&gt;Gefahrenübergang §644 -->
<g id="edge88" class="edge"><title>Werkvertrag&#45;&gt;Gefahrenübergang §644</title>
<path fill="none" stroke="black" d="M1442.46,-1250.47C1476.13,-1204.55 1529.36,-1131.96 1557.72,-1093.29"/>
<polygon fill="black" stroke="black" points="1560.62,-1095.26 1563.71,-1085.13 1554.97,-1091.12 1560.62,-1095.26"/>
</g>
<!-- Mängel_dv -->
<g id="node37" class="node"><title>Mängel_dv</title>
<polygon fill="none" stroke="black" points="1113.5,-410.5 1113.5,-657.5 1320.5,-657.5 1320.5,-410.5 1113.5,-410.5"/>
<text text-anchor="middle" x="1217" y="-624.9" font-family="Times Roman,serif" font-size="14.00"> Mängel:</text>
<polyline fill="none" stroke="black" points="1113.5,-616.5 1320.5,-616.5 "/>
<text text-anchor="middle" x="1217" y="-583.9" font-family="Times Roman,serif" font-size="14.00"> Rechte des Bestellers §634</text>
<polyline fill="none" stroke="black" points="1113.5,-575.5 1320.5,-575.5 "/>
<text text-anchor="middle" x="1217" y="-542.9" font-family="Times Roman,serif" font-size="14.00"> Verjährung §634a</text>
<polyline fill="none" stroke="black" points="1113.5,-534.5 1320.5,-534.5 "/>
<text text-anchor="middle" x="1217" y="-501.9" font-family="Times Roman,serif" font-size="14.00"> Nacherfüllung §635</text>
<polyline fill="none" stroke="black" points="1113.5,-493.5 1320.5,-493.5 "/>
<text text-anchor="middle" x="1217" y="-460.9" font-family="Times Roman,serif" font-size="14.00"> Selbstvornahme §637</text>
<polyline fill="none" stroke="black" points="1113.5,-452.5 1320.5,-452.5 "/>
<text text-anchor="middle" x="1217" y="-419.4" font-family="Times Roman,serif" font-size="14.00"> Minderung §638</text>
</g>
<!-- Besteller&#45;&gt;Mängel_dv -->
<g id="edge90" class="edge"><title>Besteller&#45;&gt;Mängel_dv</title>
<path fill="none" stroke="black" d="M1298.16,-1048.96C1288.88,-990.077 1258.87,-799.695 1238.07,-667.7"/>
<polygon fill="black" stroke="black" points="1241.48,-666.839 1236.46,-657.506 1234.56,-667.929 1241.48,-666.839"/>
</g>
<!-- Abnahme §640 -->
<g id="node38" class="node"><title>Abnahme §640</title>
<polygon fill="none" stroke="black" points="1458,-552 1338,-552 1338,-516 1458,-516 1458,-552"/>
<text text-anchor="middle" x="1398" y="-529.9" font-family="Times Roman,serif" font-size="14.00">Abnahme §640</text>
</g>
<!-- Besteller&#45;&gt;Abnahme §640 -->
<g id="edge92" class="edge"><title>Besteller&#45;&gt;Abnahme §640</title>
<path fill="none" stroke="black" d="M1304.28,-1048.96C1318.57,-970.43 1375.43,-658.012 1392.88,-562.13"/>
<polygon fill="black" stroke="black" points="1396.37,-562.5 1394.72,-552.035 1389.48,-561.246 1396.37,-562.5"/>
</g>
<!-- Vergütung §641 + §271 + §320 -->
<g id="node39" class="node"><title>Vergütung §641 + §271 + §320</title>
<polygon fill="none" stroke="black" points="1714,-552 1476,-552 1476,-516 1714,-516 1714,-552"/>
<text text-anchor="middle" x="1595" y="-529.9" font-family="Times Roman,serif" font-size="14.00">Vergütung §641 + §271 + §320</text>
</g>
<!-- Unternehmer&#45;&gt;Vergütung §641 + §271 + §320 -->
<g id="edge94" class="edge"><title>Unternehmer&#45;&gt;Vergütung §641 + §271 + §320</title>
<path fill="none" stroke="black" d="M1418.19,-1048.96C1445.21,-970.27 1552.86,-656.743 1585.54,-561.549"/>
<polygon fill="black" stroke="black" points="1588.87,-562.629 1588.81,-552.035 1582.25,-560.356 1588.87,-562.629"/>
</g>
<!-- Kündigung_dv -->
<g id="node41" class="node"><title>Kündigung_dv</title>
<polygon fill="none" stroke="black" points="1686.5,-1025.5 1686.5,-1108.5 1823.5,-1108.5 1823.5,-1025.5 1686.5,-1025.5"/>
<text text-anchor="middle" x="1755" y="-1075.9" font-family="Times Roman,serif" font-size="14.00"> Kündigung:</text>
<polyline fill="none" stroke="black" points="1686.5,-1067.5 1823.5,-1067.5 "/>
<text text-anchor="middle" x="1755" y="-1034.4" font-family="Times Roman,serif" font-size="14.00"> Schriftform §632</text>
</g>
<!-- Dienstvertrag&#45;&gt;Kündigung_dv -->
<g id="edge98" class="edge"><title>Dienstvertrag&#45;&gt;Kündigung_dv</title>
<path fill="none" stroke="black" d="M1663.01,-1273.97C1677.91,-1240.46 1710.33,-1167.51 1732.42,-1117.81"/>
<polygon fill="black" stroke="black" points="1735.69,-1119.06 1736.55,-1108.5 1729.29,-1116.22 1735.69,-1119.06"/>
</g>
<!-- Mieter -->
<g id="node43" class="node"><title>Mieter</title>
<polygon fill="none" stroke="black" points="1908,-1085 1848,-1085 1848,-1049 1908,-1049 1908,-1085"/>
<text text-anchor="middle" x="1878" y="-1062.9" font-family="Times Roman,serif" font-size="14.00">Mieter</text>
</g>
<!-- Mietvertrag&#45;&gt;Mieter -->
<g id="edge102" class="edge"><title>Mietvertrag&#45;&gt;Mieter</title>
<path fill="none" stroke="black" d="M1878,-1250.47C1878,-1205.32 1878,-1134.39 1878,-1095.27"/>
<polygon fill="black" stroke="black" points="1881.5,-1095.13 1878,-1085.13 1874.5,-1095.13 1881.5,-1095.13"/>
</g>
<!-- Kündigung -->
<g id="node45" class="node"><title>Kündigung</title>
<polygon fill="none" stroke="black" points="1926,-1025.5 1926,-1108.5 2108,-1108.5 2108,-1025.5 1926,-1025.5"/>
<text text-anchor="middle" x="2017" y="-1075.9" font-family="Times Roman,serif" font-size="14.00"> Kündigung: §314</text>
<polyline fill="none" stroke="black" points="1926,-1067.5 2108,-1067.5 "/>
<text text-anchor="middle" x="2017" y="-1034.4" font-family="Times Roman,serif" font-size="14.00"> aussderordentlich §543</text>
</g>
<!-- Mietvertrag&#45;&gt;Kündigung -->
<g id="edge104" class="edge"><title>Mietvertrag&#45;&gt;Kündigung</title>
<path fill="none" stroke="black" d="M1903.66,-1250.47C1926.9,-1212.85 1961.19,-1157.34 1985.97,-1117.23"/>
<polygon fill="black" stroke="black" points="1988.98,-1119.02 1991.26,-1108.67 1983.02,-1115.34 1988.98,-1119.02"/>
</g>
<!-- Mängel2 -->
<g id="node44" class="node"><title>Mängel2</title>
<polygon fill="none" stroke="black" points="1731.5,-451.5 1731.5,-616.5 2032.5,-616.5 2032.5,-451.5 1731.5,-451.5"/>
<text text-anchor="middle" x="1882" y="-583.9" font-family="Times Roman,serif" font-size="14.00"> Mängel:</text>
<polyline fill="none" stroke="black" points="1731.5,-575.5 2032.5,-575.5 "/>
<text text-anchor="middle" x="1882" y="-542.9" font-family="Times Roman,serif" font-size="14.00"> Mietminderung §536</text>
<polyline fill="none" stroke="black" points="1731.5,-534.5 2032.5,-534.5 "/>
<text text-anchor="middle" x="1882" y="-501.9" font-family="Times Roman,serif" font-size="14.00"> Schadens&#45;/Aufwendungsanspruch §536a</text>
<polyline fill="none" stroke="black" points="1731.5,-493.5 2032.5,-493.5 "/>
<text text-anchor="middle" x="1882" y="-460.4" font-family="Times Roman,serif" font-size="14.00"> Kenntnis von Mängeln §536b</text>
</g>
<!-- Mieter&#45;&gt;Mängel2 -->
<g id="edge106" class="edge"><title>Mieter&#45;&gt;Mängel2</title>
<path fill="none" stroke="black" d="M1878.14,-1048.96C1878.63,-983.673 1880.33,-756.734 1881.3,-626.954"/>
<polygon fill="black" stroke="black" points="1884.8,-626.655 1881.38,-616.629 1877.8,-626.602 1884.8,-626.655"/>
</g>
<!-- abändernde Annahme §150 Abs\.2&#45;&gt;Antrag -->
<g id="edge32" class="edge"><title>abändernde Annahme §150 Abs\.2&#45;&gt;Antrag</title>
<path fill="none" stroke="black" d="M1892.65,-1822.03C1870.45,-1851.5 1820.58,-1911.51 1779.11,-1959.35"/>
<polygon fill="black" stroke="black" points="1776.45,-1957.08 1772.53,-1966.92 1781.73,-1961.67 1776.45,-1957.08"/>
</g>
<!-- neuer Antrag §150 Abs\.1 -->
<g id="node48" class="node"><title>neuer Antrag §150 Abs\.1</title>
<polygon fill="none" stroke="black" points="2269,-1597 2079,-1597 2079,-1561 2269,-1561 2269,-1597"/>
<text text-anchor="middle" x="2174" y="-1574.9" font-family="Times Roman,serif" font-size="14.00">neuer Antrag §150 Abs.1</text>
</g>
<!-- Erlöschen §146&#45;&gt;neuer Antrag §150 Abs\.1 -->
<g id="edge36" class="edge"><title>Erlöschen §146&#45;&gt;neuer Antrag §150 Abs\.1</title>
<path fill="none" stroke="black" d="M2113.29,-1785.97C2124.78,-1746.8 2152.08,-1653.72 2165.82,-1606.9"/>
<polygon fill="black" stroke="black" points="2169.23,-1607.7 2168.69,-1597.12 2162.51,-1605.73 2169.23,-1607.7"/>
</g>
<!-- neuer Antrag §150 Abs\.1&#45;&gt;Antrag -->
<g id="edge38" class="edge"><title>neuer Antrag §150 Abs\.1&#45;&gt;Antrag</title>
<path fill="none" stroke="black" d="M2181.31,-1597.12C2202.7,-1653.45 2258.79,-1827.73 2178,-1928 2131.53,-1985.68 1921.67,-2012.15 1800.7,-2022.8"/>
<polygon fill="black" stroke="black" points="1800.38,-2019.32 1790.72,-2023.66 1800.98,-2026.29 1800.38,-2019.32"/>
</g>
<!-- Pflichtverletzung&#45;&gt;Verantwortlichkeit -->
<g id="edge66" class="edge"><title>Pflichtverletzung&#45;&gt;Verantwortlichkeit</title>
<path fill="none" stroke="black" d="M279.831,-1048.96C279.218,-983.673 277.089,-756.734 275.872,-626.954"/>
<polygon fill="black" stroke="black" points="279.369,-626.596 275.775,-616.629 272.369,-626.661 279.369,-626.596"/>
</g>
</g>
</svg>
